services:
  # YOUR MAIN APP DATABASE (The Destination)
  db:
    image: postgres:15
    container_name: safety_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  # TEMP DATABASE (The Source - DrugCentral)
  source_db:
    image: postgres:15
    container_name: raw_drugcentral
    environment:
      POSTGRES_PASSWORD: rawpassword
      POSTGRES_DB: drugcentral
    ports:
      - "5433:5432" # Note the different port (5433)
    volumes:
      # This trick automatically restores the dump when the container starts!
      - ./data/raw/drugcentral.sql.gz:/docker-entrypoint-initdb.d/drugcentral.sql.gz

volumes:
  pgdata: